name: Build basic stack

on:
  push:
    branches:
      - init
    paths:
      - 'stacks/basic/**'
  
# defaults:
#   run:
    # working-directory: stacks/basic

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stack Name
        run: echo STACK_NAME=storer-basic-test-$(date +%s) >> $GITHUB_ENV && echo ${{ env.STACK_NAME }}
     
      - uses: actions/checkout@v2
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - uses: aws-actions/setup-sam@v1
        with:
          version: 1.40.1
      
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build stack
        working-directory: ./stacks/basic
        run: |
          make build

      - name: Deploy integration tests stack
        working-directory: ./stacks/basic
        run: |
          make integration-test/deploy

      - name: Run integration tests
        working-directory: ./stacks/basic
        run: |
          make integration-test/run

      # make sure to manually run the cmd after debugging failed tests
      - name: Clear integration tests resources
        working-directory: ./stacks/basic
        run: |
          make integration-test/clear